# Nome da aplicação
spring.application.name=chamados
# Configuração do Banco de Dados PostgreSQL
# O Spring tentará ler SPRING_DATASOURCE_URL. Se não achar, usará localhost:5432
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Configurações do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Pefil ativo
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
# Chave secreta JWT
jwt.secret=${JWT_SECRET}
# Swagger especificação e UI
springdoc.api-docs.enabled=${SWAGGER_SPECIFICATION_ENABLED}
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED}